import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "././components/navbar"
import Footer from "./components/footer"
import Leave from './images/unsplash_GdSsWvVT2Hc.png'
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Navbar/>
      <div className="relative z-1 woverflow-hidden">
        <Image alt="bg-photo" src={Leave}  className="fixed top-[60%]  transform -translate-x-1/2 -translate-y-1/2 rotate-180" />
        <Image alt="bg-photo" src={Leave}  className="fixed top-[80%]  transform translate-x-1/2 -translate-y-1/2 rotate-180" />
      </div>
        {children}
      <Footer />
      </body>
    </html>
  );
}
